// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh3-HspWSbzjJC4ZiKAeXKknKaap6XoqQ',
    appId: '1:640289115729:web:YOUR-WEB-APP-ID',
    messagingSenderId: '640289115729',
    projectId: 'hostel-management-app-7a99c',
    authDomain: 'hostel-management-app-7a99c.firebaseapp.com',
    storageBucket: 'hostel-management-app-7a99c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3-HspWSbzjJC4ZiKAeXKknKaap6XoqQ',
    appId: '1:640289115729:android:8305eb75821acbcb213270',
    messagingSenderId: '640289115729',
    projectId: 'hostel-management-app-7a99c',
    storageBucket: 'hostel-management-app-7a99c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh3-HspWSbzjJC4ZiKAeXKknKaap6XoqQ',
    appId: '1:640289115729:ios:YOUR-IOS-APP-ID',
    messagingSenderId: '640289115729',
    projectId: 'hostel-management-app-7a99c',
    storageBucket: 'hostel-management-app-7a99c.appspot.com',
    iosClientId: 'YOUR-IOS-CLIENT-ID',
    iosBundleId: 'com.example.hostelManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh3-HspWSbzjJC4ZiKAeXKknKaap6XoqQ',
    appId: '1:640289115729:macos:YOUR-MACOS-APP-ID',
    messagingSenderId: '640289115729',
    projectId: 'hostel-management-app-7a99c',
    storageBucket: 'hostel-management-app-7a99c.appspot.com',
    iosClientId: 'YOUR-MACOS-CLIENT-ID',
    iosBundleId: 'com.example.hostelManagementApp',
  );
}
